version: "2"

services:
  web:
    build: build/web
    ports:
      - 8080:80
    volumes_from:
      - php
  php:
    build: build/php
    ports:
      - 9000:9000
    volumes:
      - ${SYMFONY_ROOT}:/srv/www

